# Generated by Django 5.0.2 on 2024-02-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Book_author', models.CharField(max_length=20)),
                ('Book_name', models.CharField(max_length=50)),
                ('publication', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
